apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-config
  namespace: test-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/exzacter/project-harbinger.git
    targetRevision: HEAD
    path: core/helm/envoy
    directory:
      include: '{common,preproduction}.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
